// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 pourOrigin;
        }

        public static unsafe _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 12) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 12) " +
                    "for command with ID 7");
            }

            var orig = new _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325();
            var comp = (Interop*)data;
            orig.pourOrigin = comp->pourOrigin;
            return orig;
        }

        public Vector3 pourOrigin;
        
        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 7;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325(
        Entity entity,
        Vector3 pourOrigin
)
        {
            Entity = entity;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.pourOrigin = pourOrigin; 
        }
        
        public static void Serialize(_2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325 commandData, IOutProtocolBitStream bitStream)
        {
            var converted_pourOrigin = commandData.pourOrigin.ToCoreVector3();
            bitStream.WriteVector3(converted_pourOrigin, FloatMeta.NoCompression());
        }
        
        public static _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var converted_pourOrigin = bitStream.ReadVector3(FloatMeta.NoCompression());
            var datapourOrigin = converted_pourOrigin.ToUnityVector3();
    
            return new _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325()
            {
                Entity = entity,
                Routing = target,
                pourOrigin = datapourOrigin
            };   
        }
    }

}