// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_6d71f34c2fab2e4439db9e8ff84f1018_be22283b658a4d83847b9d452b272ae2 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_6d71f34c2fab2e4439db9e8ff84f1018_34fe4dc50b524ee2837339c2cf77f940 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_6d71f34c2fab2e4439db9e8ff84f1018_309e17bafc2e4541bccadeb18849757e : BoolBinding
    {   
        private global::NetworkedXRGrabInteractable CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedXRGrabInteractable)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_6d71f34c2fab2e4439db9e8ff84f1018_6402872736654015195);
        public override string CoherenceComponentName => "_6d71f34c2fab2e4439db9e8ff84f1018_6402872736654015195";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isGrabbed); }
            set { CastedUnityComponent.isGrabbed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_6d71f34c2fab2e4439db9e8ff84f1018_6402872736654015195)coherenceComponent).isGrabbed;

            var simFrame = ((_6d71f34c2fab2e4439db9e8ff84f1018_6402872736654015195)coherenceComponent).isGrabbedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_6d71f34c2fab2e4439db9e8ff84f1018_6402872736654015195)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.isGrabbed = Value;
            }
            else
            {
                update.isGrabbed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isGrabbedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _6d71f34c2fab2e4439db9e8ff84f1018_6402872736654015195();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_6d71f34c2fab2e4439db9e8ff84f1018 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_6d71f34c2fab2e4439db9e8ff84f1018>();
        
        private global::LabContainer _6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e_CommandTarget;
        private global::LabContainer _6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685_CommandTarget;
        private global::LabContainer _6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825_CommandTarget;
        private global::LabContainer _6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0_CommandTarget;
        private global::LabContainer _6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["be22283b658a4d83847b9d452b272ae2"] = new Binding_6d71f34c2fab2e4439db9e8ff84f1018_be22283b658a4d83847b9d452b272ae2(),
            ["34fe4dc50b524ee2837339c2cf77f940"] = new Binding_6d71f34c2fab2e4439db9e8ff84f1018_34fe4dc50b524ee2837339c2cf77f940(),
            ["309e17bafc2e4541bccadeb18849757e"] = new Binding_6d71f34c2fab2e4439db9e8ff84f1018_309e17bafc2e4541bccadeb18849757e(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_6d71f34c2fab2e4439db9e8ff84f1018()
        {
            bakedCommandBindings.Add("66301979c5234c2a987c361c4faf709e", BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e);
            bakedCommandBindings.Add("7b2fc24ef31b45898cac636b70a2a685", BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685);
            bakedCommandBindings.Add("5ed750db24b7447fb6fd800c756b7825", BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825);
            bakedCommandBindings.Add("60e7ad10c5454398bdbfae40ceccfaf0", BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0);
            bakedCommandBindings.Add("ae2b95ce393140b6afd00abd4ee3c201", BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.AbsorbLiquid", "(System.Single)", SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e, ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e, MessageTarget.All, _6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e_CommandTarget, false);
        }
        
        private void SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e();
            
            int i = 0;
            command.addFill = (System.Single)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e();
            
            int i = 0;
            command.addFill = (System.Single)args[i++];
            
            ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e(command);
        }

        private void ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e(_6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e command)
        {
            var target = _6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e_CommandTarget;
            
            target.AbsorbLiquid((System.Single)(command.addFill));
        }
    
        private void BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.PourLiquid", "()", SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685, ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685, MessageTarget.All, _6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685_CommandTarget, false);
        }
        
        private void SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685();
            
            
            ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685(command);
        }

        private void ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685(_6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685 command)
        {
            var target = _6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685_CommandTarget;
            
            target.PourLiquid();
        }
    
        private void BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.LocalFillChange", "(System.SingleSystem.Single)", SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825, ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825, MessageTarget.All, _6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825_CommandTarget, false);
        }
        
        private void SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825();
            
            int i = 0;
            command.startFill = (System.Single)args[i++];
            command.endFill = (System.Single)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825();
            
            int i = 0;
            command.startFill = (System.Single)args[i++];
            command.endFill = (System.Single)args[i++];
            
            ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825(command);
        }

        private void ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825(_6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825 command)
        {
            var target = _6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825_CommandTarget;
            
            target.LocalFillChange((System.Single)(command.startFill),(System.Single)(command.endFill));
        }
    
        private void BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.SetHighlightAlpha", "(System.Int32)", SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0, ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0, MessageTarget.All, _6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0_CommandTarget, false);
        }
        
        private void SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0();
            
            int i = 0;
            command.alpha = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0();
            
            int i = 0;
            command.alpha = (System.Int32)args[i++];
            
            ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0(command);
        }

        private void ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0(_6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0 command)
        {
            var target = _6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0_CommandTarget;
            
            target.SetHighlightAlpha((System.Int32)(command.alpha));
        }
    
        private void BakeCommandBinding__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.Refill", "()", SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201, ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201, MessageTarget.All, _6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201_CommandTarget, false);
        }
        
        private void SendCommand__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201(MessageTarget target, object[] args)
        {
            var command = new _6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201();
            
            
            ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201(command);
        }

        private void ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201(_6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201 command)
        {
            var target = _6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201_CommandTarget;
            
            target.Refill();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e castedCommand:
                    ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_66301979c5234c2a987c361c4faf709e(castedCommand);
                    break;
                case _6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685 castedCommand:
                    ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_7b2fc24ef31b45898cac636b70a2a685(castedCommand);
                    break;
                case _6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825 castedCommand:
                    ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_5ed750db24b7447fb6fd800c756b7825(castedCommand);
                    break;
                case _6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0 castedCommand:
                    ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_60e7ad10c5454398bdbfae40ceccfaf0(castedCommand);
                    break;
                case _6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201 castedCommand:
                    ReceiveCommand__6d71f34c2fab2e4439db9e8ff84f1018_ae2b95ce393140b6afd00abd4ee3c201(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_6d71f34c2fab2e4439db9e8ff84f1018 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_6d71f34c2fab2e4439db9e8ff84f1018>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}