// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_2cc11f7011ea6284fbc47d6ea7ee0239_61c762d15dfd4e12853bac9614f99441 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_2cc11f7011ea6284fbc47d6ea7ee0239 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_2cc11f7011ea6284fbc47d6ea7ee0239>();
        
        private global::SingleFlowEffect _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["61c762d15dfd4e12853bac9614f99441"] = new Binding_2cc11f7011ea6284fbc47d6ea7ee0239_61c762d15dfd4e12853bac9614f99441(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_2cc11f7011ea6284fbc47d6ea7ee0239()
        {
            bakedCommandBindings.Add("2789653e953b4998803b84e938908325", BakeCommandBinding__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325_CommandTarget = (global::SingleFlowEffect)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("SingleFlowEffect.DisplayPour", "(UnityEngine.Vector3)", SendCommand__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325, ReceiveLocalCommand__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325, MessageTarget.All, _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325_CommandTarget, false);
        }
        
        private void SendCommand__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325(MessageTarget target, object[] args)
        {
            var command = new _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325();
            
            int i = 0;
            command.pourOrigin = (UnityEngine.Vector3)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325(MessageTarget target, object[] args)
        {
            var command = new _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325();
            
            int i = 0;
            command.pourOrigin = (UnityEngine.Vector3)args[i++];
            
            ReceiveCommand__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325(command);
        }

        private void ReceiveCommand__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325(_2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325 command)
        {
            var target = _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325_CommandTarget;
            
            target.DisplayPour((UnityEngine.Vector3)(command.pourOrigin));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325 castedCommand:
                    ReceiveCommand__2cc11f7011ea6284fbc47d6ea7ee0239_2789653e953b4998803b84e938908325(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_2cc11f7011ea6284fbc47d6ea7ee0239 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_2cc11f7011ea6284fbc47d6ea7ee0239>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}