// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_af0a75a35d1d548449d2d6cdf107e1ad_62ee10fc50ca40198dad1edad016d8fa : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_af0a75a35d1d548449d2d6cdf107e1ad_37bf406d0d804699b1f8ef863d0ff503 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_af0a75a35d1d548449d2d6cdf107e1ad_f6db89e2fa164eafb2a79722f93e9854 : BoolBinding
    {   
        private global::NetworkedXRGrabInteractable CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedXRGrabInteractable)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_af0a75a35d1d548449d2d6cdf107e1ad_8190433028052924678);
        public override string CoherenceComponentName => "_af0a75a35d1d548449d2d6cdf107e1ad_8190433028052924678";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isGrabbed); }
            set { CastedUnityComponent.isGrabbed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_af0a75a35d1d548449d2d6cdf107e1ad_8190433028052924678)coherenceComponent).isGrabbed;

            var simFrame = ((_af0a75a35d1d548449d2d6cdf107e1ad_8190433028052924678)coherenceComponent).isGrabbedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_af0a75a35d1d548449d2d6cdf107e1ad_8190433028052924678)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.isGrabbed = Value;
            }
            else
            {
                update.isGrabbed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isGrabbedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _af0a75a35d1d548449d2d6cdf107e1ad_8190433028052924678();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_af0a75a35d1d548449d2d6cdf107e1ad : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_af0a75a35d1d548449d2d6cdf107e1ad>();
        
        private global::LabContainer _af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034_CommandTarget;
        private global::LabContainer _af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7_CommandTarget;
        private global::LabContainer _af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce_CommandTarget;
        private global::LabContainer _af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["62ee10fc50ca40198dad1edad016d8fa"] = new Binding_af0a75a35d1d548449d2d6cdf107e1ad_62ee10fc50ca40198dad1edad016d8fa(),
            ["37bf406d0d804699b1f8ef863d0ff503"] = new Binding_af0a75a35d1d548449d2d6cdf107e1ad_37bf406d0d804699b1f8ef863d0ff503(),
            ["f6db89e2fa164eafb2a79722f93e9854"] = new Binding_af0a75a35d1d548449d2d6cdf107e1ad_f6db89e2fa164eafb2a79722f93e9854(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_af0a75a35d1d548449d2d6cdf107e1ad()
        {
            bakedCommandBindings.Add("8ed97fdbb76f4c56b7a74a337f0c1034", BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034);
            bakedCommandBindings.Add("15a1f847f1464bf2a3f0373bd04eadc7", BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7);
            bakedCommandBindings.Add("dcce483a152f479183e6034c9703d6ce", BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce);
            bakedCommandBindings.Add("95d2a71360b24ec29081f873c126b8cf", BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.AbsorbLiquid", "(System.Single)", SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034, ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034, MessageTarget.All, _af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034_CommandTarget, false);
        }
        
        private void SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034();
            
            int i = 0;
            command.addFill = (System.Single)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034();
            
            int i = 0;
            command.addFill = (System.Single)args[i++];
            
            ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034(command);
        }

        private void ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034(_af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034 command)
        {
            var target = _af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034_CommandTarget;
            
            target.AbsorbLiquid((System.Single)(command.addFill));
        }
    
        private void BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.PourLiquid", "()", SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7, ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7, MessageTarget.All, _af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7_CommandTarget, false);
        }
        
        private void SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7();
            
            
            ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7(command);
        }

        private void ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7(_af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7 command)
        {
            var target = _af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7_CommandTarget;
            
            target.PourLiquid();
        }
    
        private void BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.LocalFillChange", "(System.SingleSystem.Single)", SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce, ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce, MessageTarget.All, _af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce_CommandTarget, false);
        }
        
        private void SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce();
            
            int i = 0;
            command.startFill = (System.Single)args[i++];
            command.endFill = (System.Single)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce();
            
            int i = 0;
            command.startFill = (System.Single)args[i++];
            command.endFill = (System.Single)args[i++];
            
            ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce(command);
        }

        private void ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce(_af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce command)
        {
            var target = _af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce_CommandTarget;
            
            target.LocalFillChange((System.Single)(command.startFill),(System.Single)(command.endFill));
        }
    
        private void BakeCommandBinding__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf_CommandTarget = (global::LabContainer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("LabContainer.SetHighlightAlpha", "(System.Int32)", SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf, ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf, MessageTarget.All, _af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf_CommandTarget, false);
        }
        
        private void SendCommand__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf();
            
            int i = 0;
            command.alpha = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf(MessageTarget target, object[] args)
        {
            var command = new _af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf();
            
            int i = 0;
            command.alpha = (System.Int32)args[i++];
            
            ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf(command);
        }

        private void ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf(_af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf command)
        {
            var target = _af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf_CommandTarget;
            
            target.SetHighlightAlpha((System.Int32)(command.alpha));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034 castedCommand:
                    ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_8ed97fdbb76f4c56b7a74a337f0c1034(castedCommand);
                    break;
                case _af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7 castedCommand:
                    ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_15a1f847f1464bf2a3f0373bd04eadc7(castedCommand);
                    break;
                case _af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce castedCommand:
                    ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_dcce483a152f479183e6034c9703d6ce(castedCommand);
                    break;
                case _af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf castedCommand:
                    ReceiveCommand__af0a75a35d1d548449d2d6cdf107e1ad_95d2a71360b24ec29081f873c126b8cf(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_af0a75a35d1d548449d2d6cdf107e1ad Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_af0a75a35d1d548449d2d6cdf107e1ad>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}